### PR TITLE
Finished T08

### PR DESCRIPTION
**Pull request by AymenBerb**
Hello Guys,

Just finished T08.

To test my code:

1. first, run the api 
2. second, run the bot

Precision: The sendMessage() function only works within a callback function of client method (All the client.on(), client.once() etc... 

Otherwise, the bot won't be able to fetch the channel object it tries to send a message to and so it won't work.

This is the way discord.js operates and I do not think it is a problem.

### CODE REVIEW

**Comment by Ali-Alkhars** [comment]
@AymenBerb Is it ready for review?

**Comment by AymenBerb** [comment]
Not yet I am waiting to finish T09

**Comment by AymenBerb** [comment]
@TunaAtasayar Can you please update the courseRequest table with coherent records ? There is a record rn that has a frequency of 5 but only one date option, which makes the bot crash.

So guys T08 is done. If you want a test, please clone the api code of branch T24 and comment with // the call to the updateCourseRequest() function. Then run the api and then run the discord bot. All the records will automatically be sent to the channel as client announcements (as long as @TunaAtasayar updates their values).

**Review by Ali-Alkhars — CHANGES_REQUESTED** [review]
Nicely done Aymen! There are things to be added or noted:

1. You should add a catch statement in the HTTP request so the bot never crashes. Should be something like this .then().then().catch(err => console.error(err));
2. The "new_course_requests" route in branch 24 of the API doesn't do anything, that's why it's crashing.
3. I thought the ticket said to check every 15 mins. Did Anton tell you to change it?


A side note, when everything is done and approved, please let me resolve the conflicts with main

**Comment by AymenBerb** [comment]
@Ali-Alkhars To run the bot, you need to clone the branch T24 of the api. 
Yep Anton wanted it to check for new course requests every hour.

**Review by Ali-Alkhars — CHANGES_REQUESTED** [review]
Hello Aymen, I tried testing but I keep getting lots of errors in the API 24 branch, which makes it return an undefined result to the bot, then the bot returns an error because it's trying to perform operations on an undefined variable.

I have noticed that the API has two ``app.get("/new_course_requests", function (req, res)`` functions so you should delete one, but that wasn't the issue.

Could you take a look at the errors and ask for a review only after fixing the issues and thoroughly testing all cases?

**Comment by AymenBerb** [comment]
> Hello Aymen, I tried testing but I keep getting lots of errors in the API 24 branch, which makes it return an undefined result to the bot, then the bot returns an error because it's trying to perform operations on an undefined variable.
> 
> I have noticed that the API has two `app.get("/new_course_requests", function (req, res)` functions so you should delete one, but that wasn't the issue.
> 
> Could you take a look at the errors and ask for a review only after fixing the issues and thoroughly testing all cases?

Hello Ali, i don't understand where the problem is in your version since everything works perfectly for me.

It may be due to the fact that the all the course requests in the table CourseRequests had a status value of 1 (cause when you the http request to retrieve all new course requests their status automatically updates to pending) but even though the result shouldn't be undefined but rather an empty list as it is the case on my version.

Maybe you can try to use this route http://localhost:8080/change_course_requests_status_to_new that I created especially to change the course requests status from pending to new and then try to send the newCourseRequests HTTP request again. 

If that doesn't work check the logins.js file and make sure that everything is okkay.

**Review by Ali-Alkhars — APPROVED** [review]
Well done Aymen! Works fine. I would only remind you to remove that test comment and the extra getCourseRequests() call.

I will do the merging myself when Anton approves.🦊🦊

**Review by absirgue — COMMENTED** [review]
Excellent work! 
I'll approve as soon as we have a solution for clearing up the cdv when the bot starts to make sure we are fail proof to the server stoping to work

**Review by absirgue — APPROVED** [review]

**Pull request merged**
