### PR TITLE
T04 creating forms

### PR DESCRIPTION
**Pull request by Ali-Alkhars**
Hello beautiful reviewers! I believe I am done with this ticket. I do have some things to clear out:

1. To test my code, clone the repo -> run "node index.js" in the terminal to take the bot online -> call the slash command "\job" in discord.
2. This ticket is only to figure out how to create a form, so neglect the message format and the form entries. It is just to test out how forms (called modals in discord) work.
3. You might notice big differences between my code and Aymen's. It's because I adopted the approach of having commands and most functions in separate files. When merging his code I will make sure we follow this approach because it's cleaner, but both work perfectly fine.

image

### CODE REVIEW

**Review by absirgue — COMMENTED** [review]
Excellent code structure and documentation monsieur, thanks!

I just have a few questions:
- can we make it so that we check that the classID value has not been changed by the user before submitting the form ? 
- why is the classID now hard coded in the form.js file, can you confirm that you will be able to have it come from a dropdown list included in the message ?
- For the textfield that holds the classID that should not be changed. I think the wording can be a little bit different to not show that we did not know how to do better but that it is a choice. Basically we can say "do not touch unless u know what u're doing" (in a better worded way) meaning like don't touch except if you know u selected the wrong class and know the ID of the class they actually wanted.

Thanks!

**Review by AymenBerb — APPROVED** [review]
Code is very well documented and structured. Well done Ali !

**Comment by Ali-Alkhars** [comment]
@absirgue I will answer your questions in order:

1. I tried before but no because I can't know what the user has inputted until they submit.
2. The classId is not hardcoded in forms.js, it is taken as a parameter passed on from the select-menu. Only the choices in the select-menu are hardcoded in the message because it is not part of the ticket (added just to test the form).
3. I agree with you and it will be changed now.

Thanks!

**Review by absirgue — APPROVED** [review]
Very very well structured and documented code. Thanks!

This request has all it needs to be merged in. The file technique will be discussed with Aymen and tested on his ticket. If it ends up being successful and reliable, it will be able to be used in the real forms that will be created to remove the textField with the classID. To keep in mind before extending.

Amazing job thanks for the great spirit

**Pull request merged**
